### ISSUE TITLE
GUI scale always resets to the same value

### ISSUE THREAD

**Issue by LostLuma** [Blutmond-Team/CloudSettings-Mod#1]
This mod seems to always reset the GUI scale to 2 when the game launches, regardless of what the value saved online is. I've confirmed that the value on the server seems to be correct (see the screenshot from https://github.com/Blutmond-Team/CloudSettings-API/issues/9).

Aside from that this is a neat project that I've also thought about making before, thank you for publishing it :)

**Comment by Charismara** [comment]
Hey, thank you for your report. I'll fix this as soon as possible 👍

**Comment by Charismara** [comment]
Fixed in `2.0.0.3`

**Comment by LostLuma** [comment]
I've tested version 2.0.0.3 and can still reproduce the bug reliably.

What I assume causes this issue is that Minecraft starts with a small-ish window, and the largest value I can drag the GUI scale in this state is 2, so 3 is an "illegal" value until I expand / fullscreen the game window.

**Comment by Charismara** [comment]
> I've tested version 2.0.0.3 and can still reproduce the bug reliably.
> 
> What I assume causes this issue is that Minecraft starts with a small-ish window, and the largest value I can drag the GUI scale in this state is 2, so 3 is an "illegal" value until I expand / fullscreen the game window.

this doesn't happen in minecraft when the mod is not installed right? 
So minecraft should be capable of handling a "too high" value by just using the next lower value instead and using the "original" value when the window got enough space to render that scale.

Could you send me the log file and some reproduction steps so i can debug a bit around?

**Comment by LostLuma** [comment]
> this doesn't happen in minecraft when the mod is not installed right?

Nope.
> So minecraft should be capable of handling a "too high" value by just using the next lower value instead and using the "original" value when the window got enough space to render that scale.

I think the key here is that you are setting the value to a too-high value, but by default Minecraft does not change the settings like this mod does every time the game is loaded. You'd need to either apply the settings the same way Minecraft does on launch, or add a mixin to bypass this restriction for this specific case.

> Could you send me the log file and some reproduction steps so i can debug a bit around?

To reproduce simply load the game up and set the GUI scale to 3 (or even higher for testing), then restart. Once you make the game window larger post restart you will notice the UI is smaller again.

Here's logs from [first run](https://files.lostluma.net/5kuyDj.txt) and [second run](https://files.lostluma.net/Eul6HD.txt), they don't contain anything exciting.

**Comment by Charismara** [comment]
> You'd need to either apply the settings the same way Minecraft does on launch

Tbh that what i'm already doing. CloudSettings updates the `options.txt` file with the cloud data and then causes minecraft to load that file again like it would on startup. See [here](https://github.com/Blutmond-Team/CloudSettings-Mod/blob/1.20/common/src/main/java/de/blutmondgilde/cloudsettings/CloudSettings.java#L97).

The change in 2.0.0.3 basically fixed an issue where minecraft has not updated the lwjgl window it uses. [here](https://github.com/Blutmond-Team/CloudSettings-Mod/blob/1.20/common/src/main/java/de/blutmondgilde/cloudsettings/CloudSettings.java#L98)

It's kinda weird that minecraft changes the gui scale value by itself after the options get loaded again 🤔 

> To reproduce simply load the game up and set the GUI scale to 3 (or even higher for testing), then restart. Once you make the game window larger post restart you will notice the UI is smaller again.

I could reproduce this with gui scale 4 which gets changed to gui scale 3 after startup due to the initial window size.

A workaround for now would be to change the initial window size to match the desired size.

**Comment by LostLuma** [comment]
Yeah I'm aware of the workaround, but I figured you'd still want to fix this either way. Thank you though 🐈

**Comment by Charismara** [comment]
i'll work on a fix for sure. this bug seems annoying as hell xD

**Comment by Charismara** [comment]
Alright it should be fixed in `2.0.0.4`. I'll close this issue again.

Feel free to message me again if somehow the problem persists 👍 

Thank you for helping me improving this mod!
